// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZwf3DlhRWmqizZS7VIDLdftBa6H35B8',
    appId: '1:687173307347:web:8e75e68b5b613b7ea4bd26',
    messagingSenderId: '687173307347',
    projectId: 'study-app-c8202',
    authDomain: 'study-app-c8202.firebaseapp.com',
    storageBucket: 'study-app-c8202.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt795KxX22koAAapOUBlZQljBW6OS_ZNo',
    appId: '1:687173307347:android:7b610a2e36f11885a4bd26',
    messagingSenderId: '687173307347',
    projectId: 'study-app-c8202',
    storageBucket: 'study-app-c8202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACzVLqKemg40WNNg8kY0242N-olEqLBS8',
    appId: '1:687173307347:ios:0f22f7bb95dc5b8aa4bd26',
    messagingSenderId: '687173307347',
    projectId: 'study-app-c8202',
    storageBucket: 'study-app-c8202.appspot.com',
    iosClientId: '687173307347-elond32pj2mg7fd9nereff8hd82tqdg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACzVLqKemg40WNNg8kY0242N-olEqLBS8',
    appId: '1:687173307347:ios:0f22f7bb95dc5b8aa4bd26',
    messagingSenderId: '687173307347',
    projectId: 'study-app-c8202',
    storageBucket: 'study-app-c8202.appspot.com',
    iosClientId: '687173307347-elond32pj2mg7fd9nereff8hd82tqdg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
